#%RAML 0.8
title: DemoApi
version: v1

/me:
  get:
    responses:
      200:
        body:
          application/json:
            schema: |
              {"$schema":"http://json-schema.org/draft-04/schema#","id":"/","type":"object","properties":{"name":{"id":"name","type":"string"},"company":{"id":"company","type":"string"}},"required":["name"]}
/users/{userId}:
  get:
    queryParameters:
      filter:
        type: string
    responses:
      200:
        body:
          application/json:
            schema: |
              {"$schema":"http://json-schema.org/draft-04/schema#","id":"/","type":"object","properties":{"filter":{"id":"filter","type":"string"},"results":{"id":"results","type":"array","items":{"id":"0","type":"object","properties":{"name":{"id":"name","type":"string"},"company":{"id":"company","type":"string"}}}}}}
/status:
  get:
    queryParameters:
      desiredStatus:
        type: integer
        required: true
    responses:
      200:
      202:
      401:
      404:
      500:
      505:


/required:
  /boolean:
    get:
      queryParameters:
        param:
          type: boolean
          required: true
      responses:
        200:
  /date:
    get:
      queryParameters:
        param:
          type: date
          required: true
      responses:
        200:
  /integer:
    get:
      queryParameters:
        param:
          type: integer
          required: true
      responses:
        200:
  /number:
    get:
      queryParameters:
        param:
          type: number
          required: true
      responses:
        200:

/non-required:
  /boolean:
    get:
      queryParameters:
        param:
          type: boolean
      responses:
        200:
  /date:
    get:
      queryParameters:
        param:
          type: date
      responses:
        200:
  /integer:
    get:
      queryParameters:
        param:
          type: integer
      responses:
        200:
  /number:
    get:
      queryParameters:
        param:
          type: number
      responses:
        200:
        
/crud:
  get:
    queryParameters:
      id:
        type: integer
        required: true
        description: Resource ID
    responses:
      200:
  put:
    responses:
      200:
  post:
    responses:
      201:
  patch:
    responses:
      200:
      404:
  delete:
    responses:
      200:
      204:
      404: